#cython: language_level=3

# Define Parallel status macros
DEF PSTATUS_NOT_OWNED = 0x1
DEF PSTATUS_SHARED = 0x2
DEF PSTATUS_MULTISHARED = 0x4
DEF PSTATUS_INTERFACE = 0x8
DEF PSTATUS_GHOST = 0x10

# Define Parallel status operations
DEF PSTATUS_AND = 0x1
DEF PSTATUS_OR = 0x2
DEF PSTATUS_NOT = 0x3

# Define tag names
DEF PARALLEL_PARTITION_TAG_NAME = "PARALLEL_PARTITION"
DEF PARALLEL_STATUS_TAG_NAME = "__PARALLEL_STATUS"